### ISSUE TITLE
Allow placing heap outside of .data segment

### ISSUE THREAD

**Issue by stephan-gh** [jfrimmel/emballoc#30]
Thanks a lot for the very well documented crate!

I've been testing emballoc a bit for an embedded project as global allocator. I set it up like suggested in the documentation, using:

```rust
#[global_allocator]
static ALLOCATOR: emballoc::Allocator<4096> = emballoc::Allocator::new();
```

Testing with different heap sizes I noticed that having a large heap also results in large binary sizes. Because of the non-zero initialization in `Buffer::new()`, the entire heap ends up in the `.data` segment with 4 initialized bytes and the rest of it zeroed.

This means that the entire heap must be unnecessarily stored and loaded from the flash (or similar). Unfortunately, the `MaybeUninit::uninit()` in `Buffer::new()` does not seem to help for the static case because there is no way to represent such a partial initialization in the linker/final binary.

Is this something you have considered? Perhaps there is an easy solution for this that I'm missing.

I could think of one of the following approaches to avoid this:

- **Initialize to zero (-> .bss):** Perhaps it would be possible to initialize the first entry to zero and detect that case on the first allocation. That way the heap would end up in the `.bss` segment which is typically not stored as part of the binary but initialized at runtime. It's still somewhat unnecessarily zeroed completely before use but at least it would not consume space in the flash.

- **Provide a way to place the heap fully uninitialized in a custom linker section:** To avoid the unnecessary pre-initialization of the heap entirely I would expect that it's necessary to place the heap in a custom linker section that is not stored in the flash (like `.data`) but also not initialized at runtime (like `.bss`). In that case it would be fully uninitialized though, which cannot be properly distinguished from an initialized state later at runtime. I don't see a way how one would make this approach work without some unsafe call at the very beginning of the `main()` function, like [required for linked-list-allocator](https://github.com/rust-osdev/linked-list-allocator#usage) for example.

**Comment by jfrimmel** [comment]
Hi,

thank you very much for this bug report. I have to admit, that I never even though about this case and thus didn't check, in which segment an allocator is placed. Of course you're right and the allocator is placed in `.data` which is clearly suboptimal. I've implemented a simple test locally that shows the erroneous behavior.

The easy solution is to implement your first option: un-/zero-initialize the buffer and initialize it at the first usage. This is a small runtime penalty, but I think it's worth it. The implementation of this is rather simple and I already have a working prototype locally.

I'm currently unsure, whether or not to hide this lazy-initialization behind a `cargo` feature.

**Comment by stephan-gh** [comment]
Thanks a lot for your quick reply!

> I'm currently unsure, whether or not to hide this lazy-initialization behind a cargo feature.

Hm, for a crate that targets small embedded systems, I would expect that most would favor smaller binary sizes over a small extra check. I guess this could potentially just be checking if the first `Entry` is all zero (not sure how you implemented it).

It might have a slight negative effect for people using emballoc as local allocator on the stack, i.e.

```rust
let allocator = emballoc::Allocator::<64>::new(); // note: smaller size!
```

The partial initialization that is implemented currently would likely work correctly there and avoid the need for the runtime check. But I'm not sure how common this local usage really is. The price for the extra check is probably negligible anyway.

**Comment by jfrimmel** [comment]
Version [0.3.0 is released](https://crates.io/crates/emballoc/0.3.0) and should solve this problem. Thank you for your patience!
